learning_log/urls.py
from django.contrib import admin
#from django.urls import path
from django.urls import path, include
###

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('learning_logs/', include('learning_logs.urls')),
    path('', include('learning_logs.urls', namespace='learning_logs')),    
    path('users/', include('users.urls', namespace='users')),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning_logs/urls.py
"""defiune url pattterns for learning_logs"""

#from django.conf.urls  import url
from django.urls import path
from . import views
#from django.urls import include
app_name = 'learning_logs'

urlpatterns = [
    # Home page
    #THE PROPOSED WAY TO DO IN BOOK: url(r'^$', views.index, name='index'),
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    #(it appears i ca either use above format or the ladder)
    path('', views.topics, name='topics'),
    #path('topics/<int:topic_id>/', views.topic, name='topic'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
    #path('index/<int:user_id>/', views.profile_user, name='profile_user'),

]

users/urls.py
"""Defines url patterns for users."""

from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

from django.contrib import admin 
from django.conf import settings 
from django.conf.urls.static import static 
from .views import *

from django.conf.urls import url



app_name = 'users'
urlpatterns = [
    # Login page
    path('logout/', views.logout_view, name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    
    path('search/', SearchResultsView.as_view(), name='search_results'),
    #path('', views.disp_post, name='disp_post'),
    #
    path('disp_post/', views.disp_post, name='disp_post'),
    #path('<int:post_id>/', views.disp_post, name='disp_post'),
    path('create_profile/', views.create_profile, name='create_profile'),
    #path('login/', views.login, name='login'),
    #path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    #path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    # Logout page
    #path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # Registration page.
    #path('profiles_tm/<int:user_id>/', views.messaging, name='messaging'),
    #path('profiles_tm/<slug:user_id>/', views.messaging, name='messaging'),
    #path('messaging/', views.messaging, name='messaging'),   
    path('messaging/<int:user_id>/', views.messaging, name='messaging'),
    path('register/', views.register, name='register'),
    #path('image_upload/', profile_photo_view, name ='image_upload'), 
    path('profile/', profile_edit_view, name='profile_edit_view'),
    #
    path('profiles_tm/', views.profiles_tm, name ='profiles_tm'),
    path('user_post/', user_post, name='user_post'),
    path('profile_edit/', profile_edit_view, name='profile_edit_view'),
    path('profile_photo_edit/', edit_profile_photo, name='edit_profile_photo'),
      
      
    path('<int:user_id><int:chat_id>/', views.send_message, name='send_message'),
    path('messages/', views.messages, name='messages'),
    #path('search/', SearchResultsView.as_view(), name='search_results'),
    #path('search/', views.search, name='search'), 
    path('delete_comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    #path('disp_post/<int:post_id>/', views.post, name='post'),
    #path('disp_post/', views.user_post, name='user_post'),
    #path('disp_post/<int:post_id>/', views.user_post, name='user_post'),
    #path('disp_post/<int:post_id>/', views.new_comment, name='new_comment'),
    path('<int:post_id>/', views.delete_post, name='delete_post'),
    path('new_comment/<int:post_id>/', views.new_comment, name='new_comment'),
    #path('new_comment/<int:post_id>/', views.post, name='post'),
    path('profile_user/', views.profile_user, name='profile_user'), 
    path('profiles_tm/<int:user_id>/', views.profile_user, name='profile_user'),
    path('index/<int:user_id>/', views.profile_user, name='profile_user'), 
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Topic(models.Model):
    """A topic the user is learning about"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        """Return a string representation of the model."""
        #print(self.text)
        return self.text

class Entry(models.Model):
    """something specific learned about a topic"""
    #topic = models.ForeignKey(Topic)
    topic = models.ForeignKey(
    Topic,
    on_delete=models.CASCADE,
    )
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
        

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        if len(self.text) >= 50:
            """Return a string represerntation of the model"""
            return self.text[:50] + "..."
        else:
             return self.text

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 120})}

learning_logs/views.py
from django.shortcuts import render
from .models import Topic
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
#from django.core.urlresolvers import reverse 
from django.contrib.auth.decorators import login_required

from .forms import TopicForm, EntryForm
from .models import Topic, Entry

# Create your views here.
def index(request):
    """The home page for learning log"""
    return render(request, 'learning_logs/index.html')
@login_required
def topics(request):
    """show all topics"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """show all single topic and all its entries"""
    topic = Topic.objects.get(id=topic_id)
    # Make sure the topic belongs to the current user.
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    """"add a new topic"""
    if request.method != 'POST':
        # No data submitted create a blank form.
        form  = TopicForm()
    else:
        #POST data submitted; process data.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context) 


@login_required
def new_entry(request, topic_id):
    """ add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        # No data submitted: create a blank form.
        form = EntryForm()
    else:
        # POST data submitted: process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                        args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def  edit_entry(request, entry_id):
    """Edit an existing entry. """
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        # Initial request: pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                        args=[topic.id]))
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)
    

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Learning Log</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}
  
  </head>
  
  <body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        
        <h3>Social Path</h3>

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
            data-toggle="collapse" data-target="#navbar"
            aria-expanded="false" aria-controls="navbar">
            
          </button>
            <a class="navbar-brand" href="{% url 'users:disp_post' %}">
              Posts</a>
       </div>
       
       <div id="navbar" class="navbar-collapse collapse">
         <ul class="nav navbar-nav">
           <li><a href="{% url 'users:profiles_tm' %}">Profiles</a></li>
           <li><a href="{% url 'users:messages' %}"> Messages </a></li>
           <form style="text-align:center;" action="{% url 'users:search_results' %}" method="get">
             <input name="q" type="text" placeholder="Search Users">
             <button type="submit">Search</button>
           </form>
         
         </ul>

        <ul class ="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li><a href="{% url 'users:profile_user' user.id %}"><img src="{{user.profile.profile_image.profile_image.url}}" width="28">&nbsp;{{user.username}}</a></li>
            <li><a href="{% url 'users:logout' %}">log out</a></li>
          {% else %}
            <li><a href="{% url 'users:register' %}">register</a></li>
            <li><a href="{% url 'users:login' %}">Log in</a></li>
          {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      
      </div>
    </nav>

  <div class="container">

    <div class="page-header">
     {% block header %}{% endblock header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </div> <!-- /container -->

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
  
  <p>Edit entry</p>

  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">save changes</button>
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <div class='jumbotron'>
    <h1>Social Path</h1>
  </div>
{% endblock header %}

{% block content %}
  <h2>
    <a href="{% url 'users:register' %}">Register an account</a> 
  </h2>
  <h2>
    Social Path is a simple but charming social media platform where you can instant message, 
    post, comment and more to keep up with your social circles.
    you can view posts and comments but to use most of its other features you 
    must create an account and login.
  </h2>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}


{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

  <p>Add a new entry:</p>
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>add entry</button>
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Add new topic:</h2>
{% endblock header %}

{% block content %}
  
  <form action= "{% url 'learning_logs:new_topic' %}" method = 'post'
      class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">add topic</button>
    {% endbuttons %}

  </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <h2>{{ topic }}</h2>
{% endblock header %}


{% block content %}
  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
  </p>

    {% for entry in entries %}
      <div class="panel panel-default">
        <div class="panel-heading">
            <h3>
            {{ entry.date_added|date:'M d, Y H:i' }}
            <small>
              <a href="{% url 'learning_logs:edit_entry' entry.id %}">
                edit entry</a>
            </small>
          </h3>
        </div>
        <div class="panel-body">
          {{ entry.text|linebreaks|truncatewords:50 }}
        </div>
      </div> <!--panel -->
    {% empty %}
      There are no entries for this topic yet.
    {% endfor %}


{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <h1>Topics</h1>
{% endblock header %}

{% block content %}

  <ul>
    {% for topic in topics %}
      <li>
        <h3>
          <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
          <p>{{topic.id}}</p>
        </h3>
      </li>
    {% empty %}
      <li> No topic have been added yet.</li>
    {% endfor %}
  </ul>

  <h3><a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a></h3>

{% endblock content %}