learning_log/urls.py
from django.contrib import admin
#from django.urls import path
from django.urls import path, include
###

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('learning_logs/', include('learning_logs.urls')),
    path('', include('learning_logs.urls', namespace='learning_logs')),    
    path('users/', include('users.urls', namespace='users')),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning_logs/urls.py
"""defiune url pattterns for learning_logs"""

#from django.conf.urls  import url
from django.urls import path
from . import views
#from django.urls import include
app_name = 'learning_logs'

urlpatterns = [
    # Home page
    #THE PROPOSED WAY TO DO IN BOOK: url(r'^$', views.index, name='index'),
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    #(it appears i ca either use above format or the ladder)
    path('', views.topics, name='topics'),
    #path('topics/<int:topic_id>/', views.topic, name='topic'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
    #path('index/<int:user_id>/', views.profile_user, name='profile_user'),

]

users/urls.py
"""Defines url patterns for users."""

from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

from django.contrib import admin 
from django.conf import settings 
from django.conf.urls.static import static 
from .views import *

from django.conf.urls import url



app_name = 'users'
urlpatterns = [
    # Login page
    path('logout/', views.logout_view, name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    
    path('search/', SearchResultsView.as_view(), name='search_results'),
    #path('', views.disp_post, name='disp_post'),
    #
    path('disp_post/', views.disp_post, name='disp_post'),
    #path('<int:post_id>/', views.disp_post, name='disp_post'),
    path('create_profile/', views.create_profile, name='create_profile'),
    #path('login/', views.login, name='login'),
    #path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    #path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    # Logout page
    #path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # Registration page.
    #path('profiles_tm/<int:user_id>/', views.messaging, name='messaging'),
    #path('profiles_tm/<slug:user_id>/', views.messaging, name='messaging'),
    #path('messaging/', views.messaging, name='messaging'),   
    path('messaging/<int:user_id>/', views.messaging, name='messaging'),
    path('register/', views.register, name='register'),
    #path('image_upload/', profile_photo_view, name ='image_upload'), 
    path('profile/', profile_edit_view, name='profile_edit_view'),
    #
    path('profiles_tm/', views.profiles_tm, name ='profiles_tm'),
    path('user_post/', user_post, name='user_post'),
    path('profile_edit/', profile_edit_view, name='profile_edit_view'),
    path('profile_photo_edit/', edit_profile_photo, name='edit_profile_photo'),
      
      
    path('<int:user_id><int:chat_id>/', views.send_message, name='send_message'),
    path('messages/', views.messages, name='messages'),
    #path('search/', SearchResultsView.as_view(), name='search_results'),
    #path('search/', views.search, name='search'), 
    path('delete_comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    #path('disp_post/<int:post_id>/', views.post, name='post'),
    #path('disp_post/', views.user_post, name='user_post'),
    #path('disp_post/<int:post_id>/', views.user_post, name='user_post'),
    #path('disp_post/<int:post_id>/', views.new_comment, name='new_comment'),
    path('<int:post_id>/', views.delete_post, name='delete_post'),
    path('new_comment/<int:post_id>/', views.new_comment, name='new_comment'),
    #path('new_comment/<int:post_id>/', views.post, name='post'),
    path('profile_user/', views.profile_user, name='profile_user'), 
    path('profiles_tm/<int:user_id>/', views.profile_user, name='profile_user'),
    path('index/<int:user_id>/', views.profile_user, name='profile_user'), 
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/forms.py
from django.db import models

from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
#from .managers import PersonManager
from django.db import models
from .models import Profile, User_Post
from .models import *

class MessageForm(forms.ModelForm):
    text = forms.CharField(label='Message', max_length=500,
        widget=forms.Textarea(attrs={'rows':'3', 'cols': '100'}))
    class Meta:
        model = Message
        fields = ('text',)



class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', 'password1', 'password2') 

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username') 



class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio','bilingual',)



  
class ProfilePhotoForm(forms.ModelForm): 
  
    class Meta: 
        model = ProfilePhoto 
        fields = ['profile_image',] 


class Post_(forms.ModelForm):
    post_text = forms.CharField(label='New Post:', max_length=500,
        widget=forms.Textarea(attrs={'rows':'3', 'cols': '80'}))
    class Meta:
        model = User_Post
        fields = ('post_text',)
        

 

class CommentForm(forms.ModelForm):
    text = forms.CharField(label='', max_length=500,
        widget=forms.Textarea(attrs={'rows':'1', 'cols': '50'}))
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text': ''}
        

'''
class ChatForm(forms.ModelForm):
    class Meta:
         model = Chat
         fields = ['participants']
'''

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from .forms import UserForm, ProfileForm, Post_, ProfilePhotoForm
from .models import *
#from .models import User_Post, Chat, Message
from django.db import models
from django.http import HttpResponse 
from django.shortcuts import render, redirect 
from .forms import *
from django.views.generic import ListView
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.views import (
    LoginView,
)
import datetime


# Create your views here.

class login_view(LoginView):
    template_name = 'users/login.html'


def logout_view(request):
    """Log the user out."""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))



def register(request):
    """register new user"""
    if request.method != 'POST':
        user_form = UserForm()
    else:
        user_form = UserForm(data=request.POST)
        if user_form.is_valid():
            new_user = user_form.save()
            authenticated_user = authenticate(username=new_user.username,password=request.POST['password1'])
            login(request, authenticated_user)            
            return HttpResponseRedirect(reverse('users:create_profile'))
            
    context = {'user_form': user_form}
    return render(request, 'users/register.html', context)


def create_profile(request):
    if request.method != 'POST':
        # show empty form
        profile_form = ProfileForm()
        profile_photo_form = ProfilePhotoForm()
    else:
        profile_photo_form = ProfilePhotoForm(request.POST, request.FILES)
        profile_form = ProfileForm(data=request.POST)
        if profile_form.is_valid() and profile_photo_form.is_valid():
            profile_photo = profile_photo_form.save(commit=False)
            profile = profile_form.save(commit=False)
            profile.user = request.user
            profile_photo.owner = request.user
            profile.profile_image = profile_photo
            profile.save()
            profile_photo.save()          
            return HttpResponseRedirect(reverse('users:disp_post'))
            
    context = {'profile_form': profile_form, 'photo_form' : profile_photo_form}
    return render(request, 'users/create_profile.html', context)


@login_required
def profile_edit_view(request):
    user = Profile.objects.get(user=request.user.id)
    if request.method != 'POST':
        profile_form = ProfileForm(instance=request.user.profile)
        user_form = UserEditForm(instance=request.user)
     
    else:
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        user_form = UserEditForm(request.POST, instance=request.user)
        
        if profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return HttpResponseRedirect(reverse('users:disp_post'))   

        
    context = {'profile_form': profile_form, 'user_form' : user_form, 'user' : user}
    return render(request, 'users/profile_edit.html', context)


def profiles_tm(request):
    """show all topics"""
    profiles_ = User.objects.all().select_related('profile')
    profile_photos = ProfilePhoto.objects.all()
    context = {'profiles_': profiles_, 'profile_photos' : profile_photos}
    return render(request, 'users/profiles_tm.html', context)

@login_required
def user_post(request):
    if request.method != 'POST':
        form = Post_()

    else:
        form = Post_(data=request.POST) 

        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.owner = request.user
            new_post.date_added = datetime.datetime.now()
            new_post.save()
            print(new_post.id)
            return HttpResponseRedirect(reverse('users:disp_post'))

    context = {'form': form}
    return render(request, 'users/new_post.html', context)

@login_required
def disp_post(request):
    form = Post_()
    com_form = CommentForm()
    posts_ = []
    posts = User_Post.objects.all().order_by('-date_added')
    for post in posts.order_by('-date_added'):
        p = {'profile_photo' : ProfilePhoto.objects.get(owner=post.owner.id), 'post' : post, 'comments' : Comment.objects.filter(post=post.id)}
        posts_.append(p)
        
    context = {'posts_' : posts_, 'form' : form, 'com_form' : com_form}
    return render(request, 'users/posts1.html', context)




def post(request, post_id):
    post = User_Post.objects.get(id=post_id)
    comments = post.comment_set.order_by('-date_added')
    context = {'post': post, 'comments' : comments}
    return render(request, 'users/post.html', context)

@login_required
def new_comment(request, post_id):
    """ add a new entry for a particular topic."""
    post = User_Post.objects.get(id=post_id)
    if request.method != 'POST':
        # No data submitted: create a blank form.
        com_form = CommentForm()
    else:
        # POST data submitted: process data.
        com_form = CommentForm(data=request.POST)
        if com_form.is_valid():
            new_comment = com_form.save(commit=False)
            new_comment.post = post
            new_comment.owner = request.user
            new_comment.save()
            return HttpResponseRedirect(reverse('users:disp_post'))
    context = {'post': post, 'com_form': com_form}
    return render(request, 'users/new_comment.html', context)

@login_required
def profile_user(request, user_id):
    posts_ = []
    posts = User_Post.objects.filter(owner=user_id)
    for post in posts.order_by('-date_added'):
        p = {'profile_photo' : ProfilePhoto.objects.get(owner=post.owner.id), 'post' : post, 'comments' : Comment.objects.filter(post=post.id)}
        posts_.append(p)
    chats = Chat.objects.filter(user1=request.user)
    chats_ = Chat.objects.filter(user2=request.user)
    chats__ = chats | chats_
    profile = User.objects.get(id=user_id)
    profile_ = Profile.objects.get(user=user_id)
    profile_photo = ProfilePhoto.objects.get(owner_id=user_id)
    context = {'profile_photo' : profile_photo, 'profile' : profile, 'profile_' : profile_, 'posts_' : posts_}
    return render(request, 'users/profile.html', context) 

@login_required
def edit_profile_photo(request):
    user = request.user
    profile = Profile.objects.get(pk=user.id)
    profile_photo_ = ProfilePhoto.objects.get(owner_id=user.id)

    if request.method != 'POST':
        profile_photo_form = ProfilePhotoForm(instance=request.user.profilephoto)

    else:
         profile_photo_form = ProfilePhotoForm(request.POST, request.FILES)
         
         if profile_photo_form.is_valid():
            profile_photo = profile_photo_form.save(commit=False)
            profile_photo.owner = request.user
            profile.profile_image = profile_photo
            profile.save()
            profile_photo.save()
            return HttpResponseRedirect(reverse('users:disp_post'))
    context = {'user' : user, 'profile_photo' : profile_photo_, 'profile_photo_form' : profile_photo_form, 'profile' : profile}
    return render(request, 'users/edit_profile.html', context)

@login_required
def delete_post(request, post_id):
    post = User_Post.objects.get(id=post_id)
    comments = Comment.objects.filter(post=post_id)
    post.delete()
    for comment in comments:
        comment.delete()
    return HttpResponseRedirect(reverse('users:disp_post'))
    
@login_required   
def delete_comment(request, comment_id):
    comment = Comment.objects.get(id=comment_id)
    comment.delete()
    return HttpResponseRedirect(reverse('users:disp_post'))

@login_required
def messaging(request, user_id):
    user_1 = request.user
    user_2 = User.objects.get(id=user_id)
    now = datetime.datetime.now()
    if Chat.objects.filter(user1=user_1, user2=user_2):
        chat = Chat.objects.get(user1=user_1, user2=user_2)
    elif Chat.objects.filter(user2=user_1, user1=user_2):
        chat = Chat.objects.get(user2=user_1, user1=user_2)
    else:
        chat = Chat(user1=user_1, user2=user_2, created=now)
        chat.save()
    message_form = MessageForm()
    messages = Message.objects.filter(in_chat=chat)
    print(messages)
    context = {'messages' : messages, 'chat' : chat, 'user' : user_1, 'message_form' : message_form, 'user_id' : user_id}
    return render(request, 'users/chat.html', context)

@login_required
def send_message(request, chat_id, user_id):
    chat = Chat.objects.get(id=chat_id)
    if request.method != 'POST':
        message_form = MessageForm()
    else:
        # POST data submitted: process data.
        message_form = MessageForm(data=request.POST)
        #Chat.objects.filter(in_chat=chat, id=chat.id)
        if message_form.is_valid():
            #chat.save()
            print(chat)
            new_message = message_form.save(commit=False)
            new_message.in_chat = chat
            new_message.user = request.user
            new_message.save()
            return HttpResponseRedirect(reverse('users:messaging', args=[user_id]))
    
    
class SearchResultsView(ListView):
    model = User
    template_name = 'users/search_results.html'
    
    def get_queryset(self): # new
        query = self.request.GET.get('q')
        object_list = User.objects.filter(Q(first_name__icontains=query) | Q(last_name__icontains=query) | Q(username__icontains=query) | Q(username__icontains=query))
        if ' ' in query:
            object_list = User.objects.filter(Q(first_name__icontains=query) | Q(last_name__icontains=query) | Q(username__icontains=query) | Q(username__icontains=query) | Q(last_name__icontains=query.split()[0]) | Q(last_name__icontains=query.split()[1]))
        return object_list
    

users/templates/users/chat.html
{% extends "learning_logs/base.html" %}
{% block content %}
  
  <!DOCTYPE html> 
  <html lang="en">
  <head>
  <title>Profiles</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  </head>
  <body>
  
  {% for message in messages %}
    {% if message.user == user %}
      <div style="width: 40%;" class="container p-3 my-3 bg-dark text-white">
        <p style="text-align:right; font-size:15px">&nbsp;{{ message.text }}&nbsp;<img src="{{message.user.profile.profile_image.profile_image.url}}" width="60"></p>
        
      </div>
    {% else %}
      <div style="width: 40%;" class="container p-3 my-3 bg-secondary text-white">
        <p style="font-size:15px"><img src="{{message.user.profile.profile_image.profile_image.url}}" width="60">
        <a href="{% url 'users:profile_user' message.user.id %}">{{ message.user }}</a> | {{ message.text }}</p>
      </div>
    {% endif %}
  {% empty %}
    <p>
      no
    </p>
  {% endfor %}
  
  <form style="text-align:center; font-size:15px" action="{% url 'users:send_message' chat_id=chat.id user_id=user_id %}" method='POST'>
    {% csrf_token %}
    {{ message_form.as_p }}
    <button name='submit'>Send</button>
  </form> 

{% endblock content %}

users/templates/users/create_profile.html
{% extends "learning_logs/base.html" %}
{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ photo_form.as_p }}
    {{ profile_form.as_p }} 
    <button type="submit">Create</button>
  </form>
{%endblock content %}

users/templates/users/image_disp.html
{% block head %}
<title>Profile</title>
{% endblock %}

{% block content %}
    <form method = "post" enctype="multipart/form-data"> 
        {% csrf_token %} 
        {{ form.as_p }} 
        <button type="submit">Upload</button> 
    </form> 
{% endblock content %}

users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}

  <form method="post" action="{% url 'users:login' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">log in</button>
    {% endbuttons %}

    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
  </form>
{% endblock content %}

users/templates/users/new_comment.html
{% extends "learning_logs/base.html" %}


{% block content %}

  <p><a href="{% url 'users:post' post.id %}">{{ post }}</a></p>

  <p>Add a new entry:</p>
  <form action="{% url 'users:new_comment' post.id %}" method='POST'>
    {% csrf_token %}
    {{ com_form.as_p }}
    <button name='submit'>add entry</button>
  </form>
{% endblock content %}

users/templates/users/new_post.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save changes</button>
  </form>
{% endblock content %}

users/templates/users/post.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <h2>{{ post }}</h2>
{% endblock header %}


{% block content %}
  <p>
    <a href="{% url 'users:new_comment' post.id %}">add new entry</a>
  </p>

    {% for comment in comments %}
      <div class="panel panel-default">
        <div class="panel-heading">
            <h3>
            {{ comment.date_added|date:'M d, Y H:i' }}
            <small>
              <a href="{% url 'users:new_comment' comment.id %}">
                edit entry</a>
            </small>
          </h3>
        </div>
        <div class="panel-body">
          {{ comment.text|linebreaks|truncatewords:50 }}
        </div>
      </div> <!--panel -->
    {% empty %}
      There are no entries for this topic yet.
    {% endfor %}


{% endblock content %}

users/templates/users/posts _.html
{% extends "learning_logs/base.html" %}
{% block content %}

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save changes</button>
  </form>

  

    <form action="{% url 'users:new_comment' post.id %}" method='POST'>
      {% csrf_token %}
      {{ com_form.as_p }}
      <button name='submit'>Comment</button>
    </form>
  <ul><h1><a href="{% url 'users:user_post' %}">Add a new post</a></h1></ul>
{% endblock content %}

users/templates/users/posts.html
{% extends "learning_logs/base.html" %}
{% block content %}

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save changes</button>
  </form>

  {% for post in posts %}
    
      {% for profile_photo in profile_photos %} 
        {% if post.owner.id == profile_photo.owner.id %} 
          <p><a href="{% url 'users:post' post.id %}"> <img src="{{ profile_photo.get_photo_url }}" width="60"> | {{ post.owner }}</a> | {{ post }}</p>

        {% endif %}  
      {% endfor %}

      
      {% for comment in comments %}
        {% for i in comment %}
          {% for profile_photo in profile_photos %}
            {% if i.post.id == post.id %}
            {% if i.owner.id == profile_photo.owner.id %} 
              <p style="margin-left:50px; margin-right:50px;"><img src="{{ profile_photo.get_photo_url }}" width="60"> | {{i.owner}} : {{ i.text }} </p>
            {% endif %}
            {% endif %}
          
      {% endfor %}  
        {% endfor %}  
          {% endfor %}

    <form action="{% url 'users:new_comment' post.id %}" method='POST'>
      {% csrf_token %}
      {{ com_form.as_p }}
      <button name='submit'>Comment</button>
    </form>
  {% endfor %}
  <ul><h1><a href="{% url 'users:user_post' %}">Add a new post</a></h1></ul>
{% endblock content %}

users/templates/users/posts1.html
{% extends "learning_logs/base.html" %}
{% block content %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <p>
  <form action="{% url 'users:user_post' %}" method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Post</button>
  </form>
  <p>________________________________________________________________________________________________________</p>
  <p>===================================================================================================</p>
  </p>
  
  {% for post in posts_ %}
    <ul>
    
    {% for key, value in post.items %} 
      
     {% if key == 'profile_photo' %}
      <p><img src="{{ value.get_photo_url }}" width="60"></p>
     {% endif %}

     {% if key == 'post' %}
       {% if user == value.owner %}
         <p><a href="{% url 'users:delete_post' value.id %}"><i style="font-size:12px" class="fa">&#xf014;</i></a></p>
       {% endif %}
       <p><a href="{% url 'users:profile_user' value.owner.id %}">{{ value.owner }}</a></p>
       <h3>{{ value }}</h3>
     {% endif %}
     
     {% if key == 'comments' %}
       {% for val in value %}
         <img src="{{ val.owner.profile.profile_image.get_photo_url }}" width="30">
         {% if user == val.owner %}
           <a href="{% url 'users:delete_comment' val.id %}"><i style="font-size:12px" class="fa">&#xf014;</i></a>
         {% endif %}  
         <a href="{% url 'users:profile_user' val.owner.id %}"> <h6> {{val.owner}}</a>: {{val.text}}</h6>
       {% endfor %}
     {% endif %}
     
     {% if key == 'comments' %}
       <p>
       <form action="{% url 'users:new_comment' post.post.id %}" method='POST'>
           {% csrf_token %}
           {{ com_form.as_p }}
         <button name='submit'>Comment</button>
       </form> 
       <p>_______________________________________________________________________</p>
       </p>
     {% endif %}
    
   {% endfor %}
  {% endfor %}
  
  
{% endblock content %}

users/templates/users/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>

{% extends "learning_logs/base.html" %}
  {% block content %}
    <p><a href="{% url 'users:messages' %}"> Messages </a></p>
    <div class="container p-3 my-3 bg-dark text-white">
      {% if user == profile %}
        <a href="{% url 'users:profile_edit_view' %}"> edit profile </a>
      {% else %}
        <p><a href="{% url 'users:messaging' user_id=profile.id %}"> Message </a></p>
      {% endif %}
      <p><img src="{{ profile_photo.get_photo_url }}" width="240">
      
      <h1>Username: {{profile.username}}</h1>
      <h2>Name: {{ profile.first_name }} {{ profile.last_name}}</h2>
      <p>Email: {{ profile.email }}</p>
      <p>Bilingual: {{ profile_.bilingual }}</p>
      <p>Bio: {{ profile_.bio }}</p>
    </div>
  {% for post in posts_ %}
    <ul>
    
    {% for key, value in post.items %} 
      
     {% if key == 'profile_photo' %}
      <img src="{{ value.get_photo_url }}" width="60">
     {% endif %}

     {% if key == 'post' %}
       
       <p><a href="{% url 'users:profile_user' value.owner.id %}">{{ value.owner }}</a></p>
       <h3>{{ value }}</h3>
     {% endif %}
     
     {% if key == 'comments' %}
       {% for val in value %}
         <img src="{{ val.owner.profile.profile_image.get_photo_url }}" width="30">
         <a href="{% url 'users:profile_user' val.owner.id %}"> <h4> {{val.owner}}</a>: {{val}}</h4>
       {% endfor %}
     {% endif %}
   {% endfor %}
  {% endfor %}
  {% endblock content %}

users/templates/users/profile_edit.html
{% extends "learning_logs/base.html" %}

{% block content %}
  
  <p>Edit profile</p>
  <p><img src="{{ user.profile_image.get_photo_url }}" width="240"></p>
  <a href="{% url 'users:edit_profile_photo' %}"> edit profile photo </a>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ profile_form.as_p }}
    {{ user_form.as_p }} 
    {{ profile_photo_form.as_p }} 
    <button type="submit">Create</button>
  </form>
{% endblock content %}

users/templates/users/profiles_tm.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Profiles</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  
</head>
<body>
 <p style="text-align:center;" ><a href="{% url 'users:messages' %}">Messages</a></p>
 <p style="text-align:center;" ><a href="{% url 'users:disp_post' %}">Posts</a></p>
 <p style="text-align:center;"><a href="{% url 'users:profile_user' user.id %}"><img src="{{user.profile.profile_image.profile_image.url}}" width="28">&nbsp;{{user.username}}</a></p>
 
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
 <form style="text-align:center;" action="{% url 'users:search_results' %}" method="get">
  <input name="q" type="text" placeholder="Search Users">
  <button type="submit"><i class="fa fa-search"></i></button>
 </form>


</body>
{% for profile_ in profiles_ %}
  {% for profile_photo in profile_photos %}  
    <div class="container p-3 my-3 bg-dark text-white">
      {% if profile_.id == profile_photo.owner.id %}
           
        <p><a href="{% url 'users:profile_user' profile_.id %}"><h1>Username: {{ profile_ }}</h1></a></p>
        <p>Name: {{ profile_.first_name }} {{ profile_.last_name }}</p>
        <p>Bio: {{ profile_.profile.bio }}</p>
        <p>Bilingual: {{ profile_.profile.bilingual }}</p>
        <img src="{{ profile_photo.get_photo_url }}" width="240">  
        {% if user != profile_ %} 
          <p><a href="{% url 'users:messaging' user_id=profile_.id %}"> Message </a></p>
        {% endif %}
      {% endif %}
      
      {% endfor %}
    </div>
{% endfor %}
  

users/templates/users/register.html
{% extends "learning_logs/base.html" %}
{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p }} 
    <button type="submit">Create</button>
  </form>
{%endblock content %}